version: "3.8"

services:
  gliner:
    container_name: gliner
    build:
      context: .
    environment:
      - BASIC_AUTH_USER=
      - BASIC_AUTH_PASS=
      - LOG_LEVEL=DEBUG
      - WORKERS=1
      - THREADS=8
      - MODEL_DIR=/data/models
      - FINETUNED_MODEL_PATH=finetuned_model
      # 使用支持中文的多语言模型
      - GLINER_MODEL_NAME=knowledgator/gliner-x-large
      - THRESHOLD=0.4
      # 填入你的 Label Studio 地址和 API Key
      - LABEL_STUDIO_URL=http://host.docker.internal:8080
      - LABEL_STUDIO_API_KEY=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9091:9090"
    volumes:
      - "./data/server:/data"
